sendVerificationEmail:
  handler: handlers/cloudformation/sendVerificationEmail.js
verifyDomain:
  handler: handlers/cloudformation/verifyDomain.js
verifyDkim:
  Condition: ShouldCreateHostedZone
  handler: handlers/cloudformation/verifyDkim.js
createIdentityPoolMapping:
  handler: handlers/cloudformation/createIdentityPoolMapping.js
  # getStackLastUpdatedTime:
  #   handler: cfn.getStackLastUpdatedTime
