CdnDomainName: de04g0zzfvswt.cloudfront.net
DummyLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:679125707523:function:gotseason8sucks9-dev-dummy:3'
ServerlessDeploymentBucketName: gotseason8sucks9-dev-serverlessdeploymentbucket-tb30bjwk0vkn
