CdnDomainName: de04g0zzfvswt.cloudfront.net
DummyLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:679125707523:function:shudi-dev-dummy:3'
ServerlessDeploymentBucketName: shudi-dev-serverlessdeploymentbucket-tb30bjwk0vkn
