CdnDomainName: de04g0zzfvswt.cloudfront.net
DummyLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:679125707523:function:<project-name>-dev-dummy:3'
ServerlessDeploymentBucketName: <project-name>-dev-serverlessdeploymentbucket-tb30bjwk0vkn
