service:
  name: ${self:custom.environment.SERVICE}

custom:
  accountId: { Ref: AWS::AccountId }
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):dev}
  domainName: ${self:custom.environment.DOMAIN_NAME}
  userPoolId: ${self:custom.environment.USER_POOL_ID}
  output:
    handler: scripts/output.handler
    file: .build/stack.yml
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  uploadBucketName: "com-gunnertech-${self:service.name}-${self:custom.stage}"
  amplify:
    - filename: ../react-native-client/aws-exports.js
      type: javascript
    - filename: ../react-client/aws-exports.js
      type: javascript
  

plugins:
  - serverless-webpack
  - aws-amplify-serverless-plugin
  - serverless-stack-output
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.environment.REGION, 'us-east-1'}
  profile: "${self:service.name}-${opt:stage, 'dev'}developer"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - SNS:Publish
        - SES:Publish
        - SNS:*
      Resource: "*"

resources:
  Parameters:
    domainName:
      Type: String
      Default: ${self:custom.domainName}
    userPoolId:
      Type: String
      Default: ${self:custom.userPoolId}

  Conditions:
    ShouldCreateUserPoolGroups:
      Fn::Not:
        - Fn::Equals:
          - Ref: userPoolId
          - "NONE"

    ShouldCreateHostedZone:
      Fn::Not:
        - Fn::Equals:
          - Ref: domainName
          - "NONE"
      
  Outputs:
    CdnDomainName:
      Description: The domain name of the cloudfront distribution
      Value: 
        "Fn::GetAtt": [ CDN, DomainName ]

  Resources:
    CognitoUserPoolUsersGroup:
      Condition: ShouldCreateUserPoolGroups
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: Users
        UserPoolId:
          Ref: userPoolId

    CognitoUserPoolAdminsGroup:
      Condition: ShouldCreateUserPoolGroups
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: Admins
        UserPoolId:
          Ref: userPoolId

    UploadBucketPolicy: 
      Type: AWS::S3::BucketPolicy
      Properties: 
        Bucket: ${self:custom.uploadBucketName}
        PolicyDocument: 
          Statement: 
            - 
              Action: 
                - "s3:GetObject"
              Effect: "Allow"
              Resource: 
                Fn::Join: 
                  - ""
                  - 
                    - "arn:aws:s3:::"
                    - ${self:custom.uploadBucketName}
                    - "/*"
              Principal:
                AWS: { 'Fn::Join': ['', ['arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ', { 'Ref': "OriginAccessIdentity" }]] }
            - 
              Action: 
                - "s3:GetObject"
              Effect: "Allow"
              Resource: 
                Fn::Join: 
                  - ""
                  - 
                    - "arn:aws:s3:::"
                    - ${self:custom.uploadBucketName}
                    - "/*"
              Principal: '*'
    OriginAccessIdentity:
      Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
      Properties:
         CloudFrontOriginAccessIdentityConfig:
          Comment: "AccessFor"
    CDN:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          ViewerCertificate:
            CloudFrontDefaultCertificate: 'true'
          Enabled: true
          HttpVersion: http2
          Origins:
            - DomainName: "${self:custom.uploadBucketName}.s3.amazonaws.com"
              Id: "S3-${self:custom.uploadBucketName}"
              S3OriginConfig:
                OriginAccessIdentity: { 'Fn::Join': ['/', ['origin-access-identity', 'cloudfront', { 'Ref': "OriginAccessIdentity" }]] }
          DefaultCacheBehavior:
            ViewerProtocolPolicy: https-only
            TargetOriginId: "S3-${self:custom.uploadBucketName}"
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            MinTTL: 0
            ForwardedValues:
              QueryString: false
    RepoSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        Subscription:
        - Endpoint: "support@gunnertech.com"
          Protocol: email
    MyRepo:
      Type: "AWS::CodeCommit::Repository"
      DependsOn: RepoSNSTopic
      Properties:
        RepositoryName: ${self:service.name}-${self:custom.stage}
        RepositoryDescription: CodeCommit Repository
        Triggers:
        - Name: MasterTrigger
          DestinationArn:
            Ref: RepoSNSTopic
          Events:
          - all
    DNS: 
      Condition: ShouldCreateHostedZone
      Type: "AWS::Route53::HostedZone"
      Properties: 
        HostedZoneConfig: 
          Comment: "My hosted zone fore ${self:custom.domainName}"
        Name: ${self:custom.domainName}

    SMSTopic:
      Type: AWS::SNS::Topic
      Properties: 
        DisplayName: "sms${self:custom.stage}"
        TopicName: "sms${self:custom.stage}"    

functions:
  dummy: # NEED AT LEAST ONE FUNCTION OR WON'T DEPLOY
    handler: first.hello
