Parameters:
  queueName:
    Type: String
    Default: ${self:custom.environment.NOTIFICATION_QUEUE_NAME}

Resources:
  NotificationQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: 
        Ref: queueName
      VisibilityTimeout: 300
      MessageRetentionPeriod: 60
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt":
            - NotificationDeadLetterQueue
            - Arn
        maxReceiveCount: 1

  NotificationDeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: 
        Fn::Join: [ "", [ {Ref: queueName}, "DeadLetter" ] ]
      MessageRetentionPeriod: 1209600